version: "3.7"

services:
  dockerized-api:
    build: ./
    restart: unless-stopped
    volumes:
      - ./:/app:cached
    ports:
      - $API_PORT:$API_PORT
    environment:
      - API_PORT=${API_PORT}
    networks:
      - app-network

  haproxy:
    image: haproxy:latest
    ports:
      - 80:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - nginx1
      - nginx2
    networks:
      - app-network

  nginx1:
    image: nginx:latest
    ports:
      - 6001:80
    depends_on:
      - dockerized-api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

  nginx2:
    image: nginx:latest
    ports:
      - 6002:80
    depends_on:
      - dockerized-api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

networks:
  app-network:
