version: "3.7"

services:
  dockerized-api:
    build: ./
    restart: unless-stopped
    volumes:
      - ./:/app:cached
    ports:
      - $API_PORT:$API_PORT
    environment:
      - API_PORT=${API_PORT}

  nginx-cache1:
    image: nginx:latest
    depends_on:
      - dockerized-api
    links:
      - dockerized-api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  nginx-cache2:
    image: nginx:latest
    depends_on:
      - dockerized-api
    links:
      - dockerized-api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  haproxy:
    image: haproxy:latest
    ports:
      - 8000:80
    links:
      - nginx-cache1
      - nginx-cache2
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - nginx-cache1
      - nginx-cache2
